// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBchQ3Z4BRpzpuJn55Ye9z0xES8cY8Ke8I',
    appId: '1:867511776458:android:8842da241414d9c0e9b033',
    messagingSenderId: '867511776458',
    projectId: 'fir-4b-374d7',
    databaseURL: 'https://fir-4b-374d7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4b-374d7.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj4LKa2lGV0pA5JnJEi3gRGFZ0MOe6MmQ',
    appId: '1:867511776458:web:00e9bc9e504583f8e9b033',
    messagingSenderId: '867511776458',
    projectId: 'fir-4b-374d7',
    authDomain: 'fir-4b-374d7.firebaseapp.com',
    databaseURL: 'https://fir-4b-374d7-default-rtdb.firebaseio.com',
    storageBucket: 'fir-4b-374d7.appspot.com',
  );

}